POST http://localhost:4000/EmployeesUser/Add/Employee
Content-Type: application/json

{
  "EmployeeId": 39257524,
  "FullNames": "Ikou Davis Mugo",
  "Gender":"Male",
  "Age":22,
  "Contact":"0758420860",
  "Password":"As261/1163",
  "ConfirmPassword":"As261/1163",
   "Status":"active",
   "Role":"admin"

}

###
GET http://localhost:4000/EmployeesUser/Get/All/Users

###
GET http://localhost:4000/EmployeesUser/remove/All/Users











###

GET http://localhost:4000/EmployeesUser
//Content-Type: application/json

# {
#   "key1": "value1",
#   "key2": "value2"
# }